export const SET_BUSINESS_AUTH = 'SET_BUSINESS_AUTH';
export const REMOVE_AUTH = 'REMOVE_AUTH';

export const CREATE_BUSINESS_USER = 'CREATE_BUSINESS_USER';

export const UPDATE_ORDER = 'UPDATE_ORDER';
